### ISSUE TITLE
 No podspec found for `flutter_app_restart` in `.symlinks/plugins/flutter_app_restart/ios`

### ISSUE THREAD

**Issue by sunjianan9900** [SachinBhankhar/flutter_restart_plugin#3]

**Comment by forgecodex** [comment]
E/flutter (29006): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method restartApp on channel flutter_app_restart)
E/flutter (29006): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
E/flutter (29006): <asynchronous suspension>
E/flutter (29006): #1      FlutterRestart.restartApp (package:flutter_app_restart/flutter_app_restart.dart:14:22)
E/flutter (29006): <asynchronous suspension>
E/flutter (29006): #2      _MyHomePageState.build.<anonymous closure>.<anonymous closure> (package:api_ifixforu_com/main.dart:115:36)
E/flutter (29006): <asynchronous suspension>
E/flutter (29006): 
E/flutter (29006): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method restartApp on channel flutter_app_restart)
E/flutter (29006): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
E/flutter (29006): <asynchronous suspension>
E/flutter (29006): #1      FlutterRestart.restartApp (package:flutter_app_restart/flutter_app_restart.dart:14:22)
E/flutter (29006): <asynchronous suspension>
E/flutter (29006): #2      _MyHomePageState.build.<anonymous closure>.<anonymous closure> (package:api_ifixforu_com/main.dart:115:36)
E/flutter (29006): <asynchronous suspension>

**Comment by CobyReshef** [comment]
Same issue here - "No podspec found for flutter_app_restart". 
At this point the package is useless because it cannot be used for iOS.
